version: "3.9"
services:
  doxa_server:
    container_name: doxa_server
    build: .
    restart: always
    volumes:
      - "./:/app"
    ports:
      - "30003:30003"
    env_file:
      - .env

  db:
    container_name: db
    restart: always
    image: mariadb:10.9.5-jammy
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  db_data:
