version: "3.9"
services:
  doxa_server:
    container_name: doxa_server
    build: .
    restart: always
    volumes:
      - "./:/app"
    ports:
      - "30003:30003"

  db:
    container_name: db
    image: mariadb:10.9.5-jammy
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  db_data:
